import { sql } from 'drizzle-orm'
import { integer, pgSequence, pgTable, serial, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

// Order numbers come from a Postgres sequence so they are unique and never reused (ORD-10001…).
export const orderNumberSeq = pgSequence('order_number_seq', { startWith: 10001 })

// Money is stored in pence to avoid floating-point rounding.
export const orders = pgTable('orders', {
  id: serial().primaryKey(),
  number: integer().notNull().unique().default(sql`nextval('order_number_seq')`),
  // Generated by the browser once per checkout, so a retried submission returns the same order.
  checkoutId: text('checkout_id').unique(),
  customerName: text('customer_name').notNull(),
  email: text().notNull(),
  phone: text().notNull(),
  address: text().notNull(),
  city: text().notNull(),
  postcode: text().notNull(),
  country: text().notNull(),
  notes: text().notNull().default(''),
  subtotalPence: integer('subtotal_pence').notNull(),
  shippingPence: integer('shipping_pence').notNull(),
  totalPence: integer('total_pence').notNull(),
  paymentStatus: text('payment_status').notNull().default('PENDING'),
  fulfilmentStatus: text('fulfilment_status').notNull().default('NEW'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const orderItems = pgTable('order_items', {
  id: serial().primaryKey(),
  orderId: integer('order_id').notNull().references(() => orders.id),
  variantId: text('variant_id').notNull(),
  productName: text('product_name').notNull(),
  variantName: text('variant_name').notNull(),
  sku: text().notNull(),
  quantity: integer().notNull(),
  unitPricePence: integer('unit_price_pence').notNull(),
})

// Outbox for downstream channels (Slack now; SMS, email and Sheets later). One row per
// (order, event, channel), so a notification is never sent twice for the same event.
export const notifications = pgTable(
  'notifications',
  {
    id: serial().primaryKey(),
    orderId: integer('order_id').notNull().references(() => orders.id),
    channel: text().notNull(),
    event: text().notNull(),
    status: text().notNull().default('PENDING'),
    attempts: integer().notNull().default(0),
    lastError: text('last_error'),
    nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }).notNull().defaultNow(),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('notifications_order_event_channel').on(t.orderId, t.event, t.channel)],
)
