/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoreIndexRouteImport } from './routes/_store/index'
import { Route as StoreAboutRouteImport } from './routes/_store/about'
import { Route as StoreCartRouteImport } from './routes/_store/cart'
import { Route as StoreCheckoutRouteImport } from './routes/_store/checkout'
import { Route as StoreContactRouteImport } from './routes/_store/contact'
import { Route as StoreDisclaimerRouteImport } from './routes/_store/disclaimer'
import { Route as StoreOrderConfirmedRouteImport } from './routes/_store/order-confirmed'
import { Route as StorePrivacyRouteImport } from './routes/_store/privacy'
import { Route as StoreRefundsRouteImport } from './routes/_store/refunds'
import { Route as StoreShippingRouteImport } from './routes/_store/shipping'
import { Route as StoreShopRouteImport } from './routes/_store/shop'
import { Route as StoreTermsRouteImport } from './routes/_store/terms'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as StoreProductSlugRouteImport } from './routes/_store/product.$slug'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersOrderNumberRouteImport } from './routes/admin.orders.$orderNumber'

const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAboutRoute = StoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContactRoute = StoreContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => StoreRoute,
} as any)
const StoreDisclaimerRoute = StoreDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrderConfirmedRoute = StoreOrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => StoreRoute,
} as any)
const StorePrivacyRoute = StorePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRefundsRoute = StoreRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShippingRoute = StoreShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShopRoute = StoreShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoreRoute,
} as any)
const StoreTermsRoute = StoreTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => StoreRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const StoreProductSlugRoute = StoreProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersOrderNumberRoute = AdminOrdersOrderNumberRouteImport.update({
  id: '/orders/$orderNumber',
  path: '/orders/$orderNumber',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof StoreAboutRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/contact': typeof StoreContactRoute
  '/disclaimer': typeof StoreDisclaimerRoute
  '/order-confirmed': typeof StoreOrderConfirmedRoute
  '/privacy': typeof StorePrivacyRoute
  '/refunds': typeof StoreRefundsRoute
  '/shipping': typeof StoreShippingRoute
  '/shop': typeof StoreShopRoute
  '/terms': typeof StoreTermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/product/$slug': typeof StoreProductSlugRoute
  '/admin/orders/$orderNumber': typeof AdminOrdersOrderNumberRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof StoreAboutRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/contact': typeof StoreContactRoute
  '/disclaimer': typeof StoreDisclaimerRoute
  '/order-confirmed': typeof StoreOrderConfirmedRoute
  '/privacy': typeof StorePrivacyRoute
  '/refunds': typeof StoreRefundsRoute
  '/shipping': typeof StoreShippingRoute
  '/shop': typeof StoreShopRoute
  '/terms': typeof StoreTermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/': typeof StoreIndexRoute
  '/product/$slug': typeof StoreProductSlugRoute
  '/admin/orders/$orderNumber': typeof AdminOrdersOrderNumberRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_store/about': typeof StoreAboutRoute
  '/_store/cart': typeof StoreCartRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/contact': typeof StoreContactRoute
  '/_store/disclaimer': typeof StoreDisclaimerRoute
  '/_store/order-confirmed': typeof StoreOrderConfirmedRoute
  '/_store/privacy': typeof StorePrivacyRoute
  '/_store/refunds': typeof StoreRefundsRoute
  '/_store/shipping': typeof StoreShippingRoute
  '/_store/shop': typeof StoreShopRoute
  '/_store/terms': typeof StoreTermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/_store/': typeof StoreIndexRoute
  '/_store/product/$slug': typeof StoreProductSlugRoute
  '/admin/orders/$orderNumber': typeof AdminOrdersOrderNumberRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/disclaimer'
    | '/order-confirmed'
    | '/privacy'
    | '/refunds'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/admin/dashboard'
    | '/product/$slug'
    | '/admin/orders/$orderNumber'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/sitemap.xml'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/disclaimer'
    | '/order-confirmed'
    | '/privacy'
    | '/refunds'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/admin/dashboard'
    | '/'
    | '/product/$slug'
    | '/admin/orders/$orderNumber'
    | '/admin/orders'
  id:
    | '__root__'
    | '/_store'
    | '/admin'
    | '/sitemap.xml'
    | '/_store/about'
    | '/_store/cart'
    | '/_store/checkout'
    | '/_store/contact'
    | '/_store/disclaimer'
    | '/_store/order-confirmed'
    | '/_store/privacy'
    | '/_store/refunds'
    | '/_store/shipping'
    | '/_store/shop'
    | '/_store/terms'
    | '/admin/dashboard'
    | '/_store/'
    | '/_store/product/$slug'
    | '/admin/orders/$orderNumber'
    | '/admin/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/about': {
      id: '/_store/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StoreAboutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cart': {
      id: '/_store/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/contact': {
      id: '/_store/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof StoreContactRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/disclaimer': {
      id: '/_store/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof StoreDisclaimerRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/order-confirmed': {
      id: '/_store/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof StoreOrderConfirmedRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/privacy': {
      id: '/_store/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof StorePrivacyRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/refunds': {
      id: '/_store/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof StoreRefundsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/shipping': {
      id: '/_store/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof StoreShippingRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/shop': {
      id: '/_store/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof StoreShopRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/terms': {
      id: '/_store/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof StoreTermsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/product/$slug': {
      id: '/_store/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof StoreProductSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderNumber': {
      id: '/admin/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/admin/orders/$orderNumber'
      preLoaderRoute: typeof AdminOrdersOrderNumberRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface StoreRouteChildren {
  StoreAboutRoute: typeof StoreAboutRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreContactRoute: typeof StoreContactRoute
  StoreDisclaimerRoute: typeof StoreDisclaimerRoute
  StoreOrderConfirmedRoute: typeof StoreOrderConfirmedRoute
  StorePrivacyRoute: typeof StorePrivacyRoute
  StoreRefundsRoute: typeof StoreRefundsRoute
  StoreShippingRoute: typeof StoreShippingRoute
  StoreShopRoute: typeof StoreShopRoute
  StoreTermsRoute: typeof StoreTermsRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreProductSlugRoute: typeof StoreProductSlugRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAboutRoute: StoreAboutRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreContactRoute: StoreContactRoute,
  StoreDisclaimerRoute: StoreDisclaimerRoute,
  StoreOrderConfirmedRoute: StoreOrderConfirmedRoute,
  StorePrivacyRoute: StorePrivacyRoute,
  StoreRefundsRoute: StoreRefundsRoute,
  StoreShippingRoute: StoreShippingRoute,
  StoreShopRoute: StoreShopRoute,
  StoreTermsRoute: StoreTermsRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreProductSlugRoute: StoreProductSlugRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersOrderNumberRoute: typeof AdminOrdersOrderNumberRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersOrderNumberRoute: AdminOrdersOrderNumberRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
